// Code generated by protoc-gen-go. DO NOT EDIT.
// source: parker.proto

package xbospb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ParkerState struct {
	// unit: hours
	CompressorWorkingHours *Double `protobuf:"bytes,1,opt,name=compressor_working_hours,json=compressorWorkingHours,proto3" json:"compressor_working_hours,omitempty"`
	// 1=clear
	ClearCompressorWorkingHours *Int64 `protobuf:"bytes,2,opt,name=clear_compressor_working_hours,json=clearCompressorWorkingHours,proto3" json:"clear_compressor_working_hours,omitempty"`
	// 0/1/2/3=mute/reserved/mute-until-reset/restore buzzer for alarms
	BuzzerControl *Int64 `protobuf:"bytes,3,opt,name=buzzer_control,json=buzzerControl,proto3" json:"buzzer_control,omitempty"`
	// 0x0C/0x0D = stop defrost/start defrost
	DefrostControl *Int64 `protobuf:"bytes,4,opt,name=defrost_control,json=defrostControl,proto3" json:"defrost_control,omitempty"`
	// 1=resistors will be activated for 6minutes
	StartResistors *Int64 `protobuf:"bytes,5,opt,name=start_resistors,json=startResistors,proto3" json:"start_resistors,omitempty"`
	// on/standby
	OnStandbyStatus *Int64 `protobuf:"bytes,6,opt,name=on_standby_status,json=onStandbyStatus,proto3" json:"on_standby_status,omitempty"`
	LightStatus     *Int64 `protobuf:"bytes,7,opt,name=light_status,json=lightStatus,proto3" json:"light_status,omitempty"`
	AuxOutputStatus *Int64 `protobuf:"bytes,8,opt,name=aux_output_status,json=auxOutputStatus,proto3" json:"aux_output_status,omitempty"`
	// counter reduces periodically (in 1/4 of a minute)
	// unit: seconds
	NextDefrostCounter *Double `protobuf:"bytes,9,opt,name=next_defrost_counter,json=nextDefrostCounter,proto3" json:"next_defrost_counter,omitempty"`
	// digital_io_status & 0x0001
	DoorSwitchInputStatus *Bool `protobuf:"bytes,10,opt,name=door_switch_input_status,json=doorSwitchInputStatus,proto3" json:"door_switch_input_status,omitempty"`
	// digital_io_status & 0x0002
	MultipurposeInputStatus *Bool `protobuf:"bytes,11,opt,name=multipurpose_input_status,json=multipurposeInputStatus,proto3" json:"multipurpose_input_status,omitempty"`
	// digital_io_status & 0x0100
	CompressorStatus *Bool `protobuf:"bytes,12,opt,name=compressor_status,json=compressorStatus,proto3" json:"compressor_status,omitempty"`
	// digital_io_status & 0x0200
	OutputDefrostStatus *Bool `protobuf:"bytes,13,opt,name=output_defrost_status,json=outputDefrostStatus,proto3" json:"output_defrost_status,omitempty"`
	// digital_io_status & 0x0400
	FansStatus *Bool `protobuf:"bytes,14,opt,name=fans_status,json=fansStatus,proto3" json:"fans_status,omitempty"`
	// digital_io_status & 0x0800
	OutputK4Status *Bool `protobuf:"bytes,15,opt,name=output_k4_status,json=outputK4Status,proto3" json:"output_k4_status,omitempty"`
	// temperature measured by cabinet probe (in 10x actual value)
	// unit: C
	CabinetTemperature *Double `protobuf:"bytes,16,opt,name=cabinet_temperature,json=cabinetTemperature,proto3" json:"cabinet_temperature,omitempty"`
	// temperature measured by evaporator probe (in 10x actual value)
	// unit: C
	EvaporatorTemperature *Double `protobuf:"bytes,17,opt,name=evaporator_temperature,json=evaporatorTemperature,proto3" json:"evaporator_temperature,omitempty"`
	// temperature measured by auxiliary probe (if present) (in 10x actual value)
	// unit: C
	AuxiliaryTemperature *Double `protobuf:"bytes,18,opt,name=auxiliary_temperature,json=auxiliaryTemperature,proto3" json:"auxiliary_temperature,omitempty"`
	// alarm_status & 0x0100
	Probe1FailureAlarm *Bool `protobuf:"bytes,19,opt,name=probe1_failure_alarm,json=probe1FailureAlarm,proto3" json:"probe1_failure_alarm,omitempty"`
	// alarm_status & 0x0200
	Probe2FailureAlarm *Bool `protobuf:"bytes,20,opt,name=probe2_failure_alarm,json=probe2FailureAlarm,proto3" json:"probe2_failure_alarm,omitempty"`
	// alarm_status & 0x0400
	Probe3FailureAlarm *Bool `protobuf:"bytes,21,opt,name=probe3_failure_alarm,json=probe3FailureAlarm,proto3" json:"probe3_failure_alarm,omitempty"`
	// alarm_status & 0x1000
	MinimumTemperatureAlarm *Bool `protobuf:"bytes,22,opt,name=minimum_temperature_alarm,json=minimumTemperatureAlarm,proto3" json:"minimum_temperature_alarm,omitempty"`
	// alarm_status & 0x2000
	MaximumTempertureAlarm *Bool `protobuf:"bytes,23,opt,name=maximum_temperture_alarm,json=maximumTempertureAlarm,proto3" json:"maximum_temperture_alarm,omitempty"`
	// alarm_status & 0x4000
	CondensorTemperatureFailureAlarm *Bool `protobuf:"bytes,24,opt,name=condensor_temperature_failure_alarm,json=condensorTemperatureFailureAlarm,proto3" json:"condensor_temperature_failure_alarm,omitempty"`
	// alarm_status & 0x8000
	CondensorPreAlarm *Bool `protobuf:"bytes,25,opt,name=condensor_pre_alarm,json=condensorPreAlarm,proto3" json:"condensor_pre_alarm,omitempty"`
	// alarm_status & 0x0004
	DoorAlarm *Bool `protobuf:"bytes,26,opt,name=door_alarm,json=doorAlarm,proto3" json:"door_alarm,omitempty"`
	// alarm_status & 0x0008
	MultipurposeInputAlarm *Bool `protobuf:"bytes,27,opt,name=multipurpose_input_alarm,json=multipurposeInputAlarm,proto3" json:"multipurpose_input_alarm,omitempty"`
	// alarm_status & 0x0010
	CompressorBlockedAlarm *Bool `protobuf:"bytes,28,opt,name=compressor_blocked_alarm,json=compressorBlockedAlarm,proto3" json:"compressor_blocked_alarm,omitempty"`
	// alarm_status & 0x0020
	PowerFailureAlarm *Bool `protobuf:"bytes,29,opt,name=power_failure_alarm,json=powerFailureAlarm,proto3" json:"power_failure_alarm,omitempty"`
	// alarm_status & 0x0080
	RtcErrorAlarm *Bool `protobuf:"bytes,30,opt,name=rtc_error_alarm,json=rtcErrorAlarm,proto3" json:"rtc_error_alarm,omitempty"`
	// regulator_flag_1 & 0x0100
	EnergySavingRegulatorFlag *Bool `protobuf:"bytes,31,opt,name=energy_saving_regulator_flag,json=energySavingRegulatorFlag,proto3" json:"energy_saving_regulator_flag,omitempty"`
	// regulator_flag_1 & 0x0200
	EnergySavingRealTimeRegulatorFlag *Bool `protobuf:"bytes,32,opt,name=energy_saving_real_time_regulator_flag,json=energySavingRealTimeRegulatorFlag,proto3" json:"energy_saving_real_time_regulator_flag,omitempty"`
	// regulator_flag_1 & 0x0400
	ServiceRequestRegulatorFlag *Bool `protobuf:"bytes,33,opt,name=service_request_regulator_flag,json=serviceRequestRegulatorFlag,proto3" json:"service_request_regulator_flag,omitempty"`
	// regulator_flag_2 & 0x0001; 1=standby
	OnStandbyRegulatorFlag *Bool `protobuf:"bytes,34,opt,name=on_standby_regulator_flag,json=onStandbyRegulatorFlag,proto3" json:"on_standby_regulator_flag,omitempty"`
	// regulator_flag_2 & 0x0080
	NewAlarmToReadRegulatorFlag *Bool `protobuf:"bytes,35,opt,name=new_alarm_to_read_regulator_flag,json=newAlarmToReadRegulatorFlag,proto3" json:"new_alarm_to_read_regulator_flag,omitempty"`
	// regulator_flag_2 & 0x0700; 0/1/2/3 = no defrost active/defrost running/dripping/fans stop
	DefrostStatusRegulatorFlag *Int64 `protobuf:"bytes,36,opt,name=defrost_status_regulator_flag,json=defrostStatusRegulatorFlag,proto3" json:"defrost_status_regulator_flag,omitempty"`
	// active_setpoint=setpoint(when no energy saving); else=setpoint+r4
	// unit: C
	ActiveSetpoint *Double `protobuf:"bytes,37,opt,name=active_setpoint,json=activeSetpoint,proto3" json:"active_setpoint,omitempty"`
	// time remaining to next defrost
	// unit: seconds
	TimeUntilDefrost *Double `protobuf:"bytes,38,opt,name=time_until_defrost,json=timeUntilDefrost,proto3" json:"time_until_defrost,omitempty"`
	// current defrost counter countdown (in 1/4 of a minute)
	// unit: seconds
	CurrentDefrostCounter *Double `protobuf:"bytes,39,opt,name=current_defrost_counter,json=currentDefrostCounter,proto3" json:"current_defrost_counter,omitempty"`
	// compressor delay in seconds
	// unit: seconds
	CompressorDelay *Double `protobuf:"bytes,40,opt,name=compressor_delay,json=compressorDelay,proto3" json:"compressor_delay,omitempty"`
	// number of HACCP alarms in history (max of last 9 stored)
	NumAlarmsInHistory *Int64 `protobuf:"bytes,41,opt,name=num_alarms_in_history,json=numAlarmsInHistory,proto3" json:"num_alarms_in_history,omitempty"`
	// is energy saving mode active or not; digital_output_flags & 0x0100
	EnergySavingStatus *Bool `protobuf:"bytes,42,opt,name=energy_saving_status,json=energySavingStatus,proto3" json:"energy_saving_status,omitempty"`
	// digital_output_flags & 0x0200
	ServiceRequestStatus *Bool `protobuf:"bytes,43,opt,name=service_request_status,json=serviceRequestStatus,proto3" json:"service_request_status,omitempty"`
	// digital_output_flags & 0x001
	ResistorsActivatedByAuxKeyStatus *Bool `protobuf:"bytes,44,opt,name=resistors_activated_by_aux_key_status,json=resistorsActivatedByAuxKeyStatus,proto3" json:"resistors_activated_by_aux_key_status,omitempty"`
	// digital_output_flags & 0x002
	EvaporatorValveState *Bool `protobuf:"bytes,45,opt,name=evaporator_valve_state,json=evaporatorValveState,proto3" json:"evaporator_valve_state,omitempty"`
	// digital_output_flags & 0x004
	OutputDefrostState *Bool `protobuf:"bytes,46,opt,name=output_defrost_state,json=outputDefrostState,proto3" json:"output_defrost_state,omitempty"`
	// digital_output_flags & 0x008
	OutputLuxState *Bool `protobuf:"bytes,47,opt,name=output_lux_state,json=outputLuxState,proto3" json:"output_lux_state,omitempty"`
	// digital_output_flags & 0x0010
	OutputAuxState *Bool `protobuf:"bytes,48,opt,name=output_aux_state,json=outputAuxState,proto3" json:"output_aux_state,omitempty"`
	// activated by cabinet probe; digital_output_flags & 0x0020
	ResistorsState *Bool `protobuf:"bytes,49,opt,name=resistors_state,json=resistorsState,proto3" json:"resistors_state,omitempty"`
	// digital_output_flags & 0x0040
	OutputAlarmState *Bool `protobuf:"bytes,50,opt,name=output_alarm_state,json=outputAlarmState,proto3" json:"output_alarm_state,omitempty"`
	// digital_output_flags & 0x0080
	SecondCompressorState *Bool `protobuf:"bytes,51,opt,name=second_compressor_state,json=secondCompressorState,proto3" json:"second_compressor_state,omitempty"`
	// setpoint
	Setpoint *Double `protobuf:"bytes,52,opt,name=setpoint,proto3" json:"setpoint,omitempty"`
	// write=1 to clear HACCP list
	ClearAlarmHistory *Int64 `protobuf:"bytes,53,opt,name=clear_alarm_history,json=clearAlarmHistory,proto3" json:"clear_alarm_history,omitempty"`
	// write=1 to clear latest alarm flag
	ClearnNewAlarmFlag *Int64 `protobuf:"bytes,54,opt,name=clearn_new_alarm_flag,json=clearnNewAlarmFlag,proto3" json:"clearn_new_alarm_flag,omitempty"`
	// HACCP0_date + HACCP0_time
	HACCP0_Datetime *Uint64 `protobuf:"bytes,55,opt,name=HACCP0_Datetime,json=HACCP0Datetime,proto3" json:"HACCP0_Datetime,omitempty"`
	// b15-b13 of HACCP0_alarm_info
	HACCP0AlarmType *Int64 `protobuf:"bytes,56,opt,name=HACCP0_alarm_type,json=HACCP0AlarmType,proto3" json:"HACCP0_alarm_type,omitempty"`
	// using hour duration and minute duration from HACCP0_alarm_info
	// unit: minutes
	HACCP0Duration *Double `protobuf:"bytes,57,opt,name=HACCP0_duration,json=HACCP0Duration,proto3" json:"HACCP0_duration,omitempty"`
	// value@0x0504: temperature
	// unit: C
	HACCP0Temperature *Double `protobuf:"bytes,58,opt,name=HACCP0_temperature,json=HACCP0Temperature,proto3" json:"HACCP0_temperature,omitempty"`
	// HACCP1_date + HACCP1_time
	HACCP1_Datetime *Uint64 `protobuf:"bytes,59,opt,name=HACCP1_Datetime,json=HACCP1Datetime,proto3" json:"HACCP1_Datetime,omitempty"`
	// b15-b13 of HACCP1_alarm_info
	HACCP1AlarmType *Int64 `protobuf:"bytes,60,opt,name=HACCP1_alarm_type,json=HACCP1AlarmType,proto3" json:"HACCP1_alarm_type,omitempty"`
	// using hour duration and minute duration from HACCP1_alarm_info
	// unit: minutes
	HACCP1Duration *Double `protobuf:"bytes,61,opt,name=HACCP1_duration,json=HACCP1Duration,proto3" json:"HACCP1_duration,omitempty"`
	// value@0x0508: temperature
	// unit: C
	HACCP1Temperature *Double `protobuf:"bytes,62,opt,name=HACCP1_temperature,json=HACCP1Temperature,proto3" json:"HACCP1_temperature,omitempty"`
	// HACCP2_date + HACCP2_time
	HACCP2_Datetime *Uint64 `protobuf:"bytes,63,opt,name=HACCP2_Datetime,json=HACCP2Datetime,proto3" json:"HACCP2_Datetime,omitempty"`
	// b15-b13 of HACCP2_alarm_info
	HACCP2AlarmType *Int64 `protobuf:"bytes,64,opt,name=HACCP2_alarm_type,json=HACCP2AlarmType,proto3" json:"HACCP2_alarm_type,omitempty"`
	// using hour duration and minute duration from HACCP2_alarm_info
	// unit: minutes
	HACCP2Duration *Double `protobuf:"bytes,65,opt,name=HACCP2_duration,json=HACCP2Duration,proto3" json:"HACCP2_duration,omitempty"`
	// value@0x050C: temperature
	// unit: C
	HACCP2Temperature *Double `protobuf:"bytes,66,opt,name=HACCP2_temperature,json=HACCP2Temperature,proto3" json:"HACCP2_temperature,omitempty"`
	// HACCP3_date + HACCP3_time
	HACCP3_Datetime *Uint64 `protobuf:"bytes,67,opt,name=HACCP3_Datetime,json=HACCP3Datetime,proto3" json:"HACCP3_Datetime,omitempty"`
	// b15-b13 of HACCP3_alarm_info
	HACCP3AlarmType *Int64 `protobuf:"bytes,68,opt,name=HACCP3_alarm_type,json=HACCP3AlarmType,proto3" json:"HACCP3_alarm_type,omitempty"`
	// using hour duration and minute duration from HACCP3_alarm_info
	// unit: minutes
	HACCP3Duration *Double `protobuf:"bytes,69,opt,name=HACCP3_duration,json=HACCP3Duration,proto3" json:"HACCP3_duration,omitempty"`
	// value@0x0510: temperature
	// unit: C
	HACCP3Temperature *Double `protobuf:"bytes,70,opt,name=HACCP3_temperature,json=HACCP3Temperature,proto3" json:"HACCP3_temperature,omitempty"`
	// HACCP4_date + HACCP4_time
	HACCP4_Datetime *Uint64 `protobuf:"bytes,71,opt,name=HACCP4_Datetime,json=HACCP4Datetime,proto3" json:"HACCP4_Datetime,omitempty"`
	// b15-b13 of HACCP4_alarm_info
	HACCP4AlarmType *Int64 `protobuf:"bytes,72,opt,name=HACCP4_alarm_type,json=HACCP4AlarmType,proto3" json:"HACCP4_alarm_type,omitempty"`
	// using hour duration and minute duration from HACCP4_alarm_info
	// unit: minutes
	HACCP4Duration *Double `protobuf:"bytes,73,opt,name=HACCP4_duration,json=HACCP4Duration,proto3" json:"HACCP4_duration,omitempty"`
	// value@0x0514: temperature
	// unit: C
	HACCP4Temperature *Double `protobuf:"bytes,74,opt,name=HACCP4_temperature,json=HACCP4Temperature,proto3" json:"HACCP4_temperature,omitempty"`
	// HACCP5_date + HACCP5_time
	HACCP5_Datetime *Uint64 `protobuf:"bytes,75,opt,name=HACCP5_Datetime,json=HACCP5Datetime,proto3" json:"HACCP5_Datetime,omitempty"`
	// b15-b13 of HACCP5_alarm_info
	HACCP5AlarmType *Int64 `protobuf:"bytes,76,opt,name=HACCP5_alarm_type,json=HACCP5AlarmType,proto3" json:"HACCP5_alarm_type,omitempty"`
	// using hour duration and minute duration from HACCP5_alarm_info
	// unit: minutes
	HACCP5Duration *Double `protobuf:"bytes,77,opt,name=HACCP5_duration,json=HACCP5Duration,proto3" json:"HACCP5_duration,omitempty"`
	// value@0x0518: temperature
	// unit: C
	HACCP5Temperature *Double `protobuf:"bytes,78,opt,name=HACCP5_temperature,json=HACCP5Temperature,proto3" json:"HACCP5_temperature,omitempty"`
	// HACCP6_date + HACCP6_time
	HACCP6_Datetime *Uint64 `protobuf:"bytes,79,opt,name=HACCP6_Datetime,json=HACCP6Datetime,proto3" json:"HACCP6_Datetime,omitempty"`
	// b15-b13 of HACCP6_alarm_info
	HACCP6AlarmType *Int64 `protobuf:"bytes,80,opt,name=HACCP6_alarm_type,json=HACCP6AlarmType,proto3" json:"HACCP6_alarm_type,omitempty"`
	// using hour duration and minute duration from HACCP6_alarm_info
	// unit: minutes
	HACCP6Duration *Double `protobuf:"bytes,81,opt,name=HACCP6_duration,json=HACCP6Duration,proto3" json:"HACCP6_duration,omitempty"`
	// value@0x051C: temperature
	// unit: C
	HACCP6Temperature *Double `protobuf:"bytes,82,opt,name=HACCP6_temperature,json=HACCP6Temperature,proto3" json:"HACCP6_temperature,omitempty"`
	// HACCP7_date + HACCP7_time
	HACCP7_Datetime *Uint64 `protobuf:"bytes,83,opt,name=HACCP7_Datetime,json=HACCP7Datetime,proto3" json:"HACCP7_Datetime,omitempty"`
	// b15-b13 of HACCP7_alarm_info
	HACCP7AlarmType *Int64 `protobuf:"bytes,84,opt,name=HACCP7_alarm_type,json=HACCP7AlarmType,proto3" json:"HACCP7_alarm_type,omitempty"`
	// using hour duration and minute duration from HACCP7_alarm_info
	// unit: minutes
	HACCP7Duration *Double `protobuf:"bytes,85,opt,name=HACCP7_duration,json=HACCP7Duration,proto3" json:"HACCP7_duration,omitempty"`
	// value@0x0520: temperature
	// unit: C
	HACCP7Temperature *Double `protobuf:"bytes,86,opt,name=HACCP7_temperature,json=HACCP7Temperature,proto3" json:"HACCP7_temperature,omitempty"`
	// HACCP8_date + HACCP8_time
	HACCP8_Datetime *Uint64 `protobuf:"bytes,87,opt,name=HACCP8_Datetime,json=HACCP8Datetime,proto3" json:"HACCP8_Datetime,omitempty"`
	// b15-b13 of HACCP8_alarm_info
	HACCP8AlarmType *Int64 `protobuf:"bytes,88,opt,name=HACCP8_alarm_type,json=HACCP8AlarmType,proto3" json:"HACCP8_alarm_type,omitempty"`
	// using hour duration and minute duration from HACCP8_alarm_info
	// unit: minutes
	HACCP8Duration *Double `protobuf:"bytes,89,opt,name=HACCP8_duration,json=HACCP8Duration,proto3" json:"HACCP8_duration,omitempty"`
	// value@0x0524: temperature
	// unit: C
	HACCP8Temperature *Double `protobuf:"bytes,90,opt,name=HACCP8_temperature,json=HACCP8Temperature,proto3" json:"HACCP8_temperature,omitempty"`
	// min working setpoint
	// unit: C
	R1 *Double `protobuf:"bytes,91,opt,name=r1,proto3" json:"r1,omitempty"`
	// max working setpoint
	// unit: C
	R2 *Double `protobuf:"bytes,92,opt,name=r2,proto3" json:"r2,omitempty"`
	// used for active_set_point calculation in energy saving mode; adds to active setpoint
	R4 *Double `protobuf:"bytes,93,opt,name=r4,proto3" json:"r4,omitempty"`
	// compressor delay after turning on controller
	// unit: minutes
	C0 *Double `protobuf:"bytes,94,opt,name=C0,proto3" json:"C0,omitempty"`
	// min time between 2 activations in succession of compressor
	// unit: minutes
	C1 *Double `protobuf:"bytes,95,opt,name=C1,proto3" json:"C1,omitempty"`
	// defrost interval (only if d8 = 0/1/2); 0 = the defrost at intervals will never be activated
	// unit: hours
	D0 *Double `protobuf:"bytes,96,opt,name=d0,proto3" json:"d0,omitempty"`
	// defrost duration if P3=0 or 2; max duration if P3=1
	// unit: minutes
	D3 *Double `protobuf:"bytes,97,opt,name=d3,proto3" json:"d3,omitempty"`
	// defrost delay when you turn on controller; only if d4=1
	// unit: minutes
	D5 *Double `protobuf:"bytes,98,opt,name=d5,proto3" json:"d5,omitempty"`
	// drip delay
	// unit: minutes
	D7 *Double `protobuf:"bytes,99,opt,name=d7,proto3" json:"d7,omitempty"`
	// kind of defrost interval; 0/1/2/3=defrost on when controller/compressor/evaporator temperature is below d9  is on for d0 hours/realtime
	D8 *Int64 `protobuf:"bytes,100,opt,name=d8,proto3" json:"d8,omitempty"`
	// measured input for low temp alarm; 0/1/2=cab/evap/aux (only if P4=1/2)
	A0 *Int64 `protobuf:"bytes,101,opt,name=A0,proto3" json:"A0,omitempty"`
	// temperature below which low temperature alarm is activated
	// unit: C
	A1 *Double `protobuf:"bytes,102,opt,name=A1,proto3" json:"A1,omitempty"`
	// kind of lower temp alarm; 0/1/2=disabled/working setpoint-A1/absolute (or A1)
	A2 *Int64 `protobuf:"bytes,103,opt,name=A2,proto3" json:"A2,omitempty"`
	// measured input for high temp alarm; 0/1/2=cab/evap/aux (only if P4=1/2)
	A3 *Int64 `protobuf:"bytes,104,opt,name=A3,proto3" json:"A3,omitempty"`
	// temperature above which high temperature alarm is activated
	// unit: C
	A4 *Double `protobuf:"bytes,105,opt,name=A4,proto3" json:"A4,omitempty"`
	// kind of high temp alarm; 0/1/2=disabled/working setpoint+A4/absolute (or A4)
	A5 *Int64 `protobuf:"bytes,106,opt,name=A5,proto3" json:"A5,omitempty"`
	// high temperature alarm delay after turning on controller; only if A3=0
	// unit: minutes
	A6 *Double `protobuf:"bytes,107,opt,name=A6,proto3" json:"A6,omitempty"`
	// temperature alarm delay
	// unit: minutes
	A7 *Double `protobuf:"bytes,108,opt,name=A7,proto3" json:"A7,omitempty"`
	// high temperature alarm delay after end of defrost; only if A3=0
	// unit: minutes
	A8 *Double `protobuf:"bytes,109,opt,name=A8,proto3" json:"A8,omitempty"`
	// high temperature alarm delay after deactivation of microport input only if A3=0
	// unit: minutes
	A9 *Double `protobuf:"bytes,110,opt,name=A9,proto3" json:"A9,omitempty"`
	// evap fan activity during normal operation; 0/1/2/3/4=off/on/in parallel with compressor/dependent on F1/off if compressor is off and depedent on F1 if compressor is on
	F0 *Int64 `protobuf:"bytes,111,opt,name=F0,proto3" json:"F0,omitempty"`
	// evap temperature above which evap fan is turned off; only if F0=3/4
	// unit: C
	F1 *Double `protobuf:"bytes,112,opt,name=F1,proto3" json:"F1,omitempty"`
	// evap fan activity during defrost and drip delay; 0/1/2 = off/on/dependent on F0
	F2 *Int64 `protobuf:"bytes,113,opt,name=F2,proto3" json:"F2,omitempty"`
	// fan delay after evap drip completes
	// unit: minutes
	F3 *Double `protobuf:"bytes,114,opt,name=F3,proto3" json:"F3,omitempty"`
	// first real time defrost activation time; only if d8=3
	// unit: hh:mm
	Hd1 string `protobuf:"bytes,115,opt,name=Hd1,proto3" json:"Hd1,omitempty"`
	// second real time defrost activation time; only if d8=3
	// unit: hh:mm
	Hd2 string `protobuf:"bytes,116,opt,name=Hd2,proto3" json:"Hd2,omitempty"`
	// third real time defrost activation time; only if d8=3
	// unit: hh:mm
	Hd3 string `protobuf:"bytes,117,opt,name=Hd3,proto3" json:"Hd3,omitempty"`
	// fourth real time defrost activation time; only if d8=3
	// unit: hh:mm
	Hd4 string `protobuf:"bytes,118,opt,name=Hd4,proto3" json:"Hd4,omitempty"`
	// fifth real time defrost activation time; only if d8=3
	// unit: hh:mm
	Hd5 string `protobuf:"bytes,119,opt,name=Hd5,proto3" json:"Hd5,omitempty"`
	// sixth real time defrost activation time; only if d8=3
	// unit: hh:mm
	Hd6                  string   `protobuf:"bytes,120,opt,name=Hd6,proto3" json:"Hd6,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParkerState) Reset()         { *m = ParkerState{} }
func (m *ParkerState) String() string { return proto.CompactTextString(m) }
func (*ParkerState) ProtoMessage()    {}
func (*ParkerState) Descriptor() ([]byte, []int) {
	return fileDescriptor_parker_b0359a1265356f03, []int{0}
}
func (m *ParkerState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParkerState.Unmarshal(m, b)
}
func (m *ParkerState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParkerState.Marshal(b, m, deterministic)
}
func (dst *ParkerState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParkerState.Merge(dst, src)
}
func (m *ParkerState) XXX_Size() int {
	return xxx_messageInfo_ParkerState.Size(m)
}
func (m *ParkerState) XXX_DiscardUnknown() {
	xxx_messageInfo_ParkerState.DiscardUnknown(m)
}

var xxx_messageInfo_ParkerState proto.InternalMessageInfo

func (m *ParkerState) GetCompressorWorkingHours() *Double {
	if m != nil {
		return m.CompressorWorkingHours
	}
	return nil
}

func (m *ParkerState) GetClearCompressorWorkingHours() *Int64 {
	if m != nil {
		return m.ClearCompressorWorkingHours
	}
	return nil
}

func (m *ParkerState) GetBuzzerControl() *Int64 {
	if m != nil {
		return m.BuzzerControl
	}
	return nil
}

func (m *ParkerState) GetDefrostControl() *Int64 {
	if m != nil {
		return m.DefrostControl
	}
	return nil
}

func (m *ParkerState) GetStartResistors() *Int64 {
	if m != nil {
		return m.StartResistors
	}
	return nil
}

func (m *ParkerState) GetOnStandbyStatus() *Int64 {
	if m != nil {
		return m.OnStandbyStatus
	}
	return nil
}

func (m *ParkerState) GetLightStatus() *Int64 {
	if m != nil {
		return m.LightStatus
	}
	return nil
}

func (m *ParkerState) GetAuxOutputStatus() *Int64 {
	if m != nil {
		return m.AuxOutputStatus
	}
	return nil
}

func (m *ParkerState) GetNextDefrostCounter() *Double {
	if m != nil {
		return m.NextDefrostCounter
	}
	return nil
}

func (m *ParkerState) GetDoorSwitchInputStatus() *Bool {
	if m != nil {
		return m.DoorSwitchInputStatus
	}
	return nil
}

func (m *ParkerState) GetMultipurposeInputStatus() *Bool {
	if m != nil {
		return m.MultipurposeInputStatus
	}
	return nil
}

func (m *ParkerState) GetCompressorStatus() *Bool {
	if m != nil {
		return m.CompressorStatus
	}
	return nil
}

func (m *ParkerState) GetOutputDefrostStatus() *Bool {
	if m != nil {
		return m.OutputDefrostStatus
	}
	return nil
}

func (m *ParkerState) GetFansStatus() *Bool {
	if m != nil {
		return m.FansStatus
	}
	return nil
}

func (m *ParkerState) GetOutputK4Status() *Bool {
	if m != nil {
		return m.OutputK4Status
	}
	return nil
}

func (m *ParkerState) GetCabinetTemperature() *Double {
	if m != nil {
		return m.CabinetTemperature
	}
	return nil
}

func (m *ParkerState) GetEvaporatorTemperature() *Double {
	if m != nil {
		return m.EvaporatorTemperature
	}
	return nil
}

func (m *ParkerState) GetAuxiliaryTemperature() *Double {
	if m != nil {
		return m.AuxiliaryTemperature
	}
	return nil
}

func (m *ParkerState) GetProbe1FailureAlarm() *Bool {
	if m != nil {
		return m.Probe1FailureAlarm
	}
	return nil
}

func (m *ParkerState) GetProbe2FailureAlarm() *Bool {
	if m != nil {
		return m.Probe2FailureAlarm
	}
	return nil
}

func (m *ParkerState) GetProbe3FailureAlarm() *Bool {
	if m != nil {
		return m.Probe3FailureAlarm
	}
	return nil
}

func (m *ParkerState) GetMinimumTemperatureAlarm() *Bool {
	if m != nil {
		return m.MinimumTemperatureAlarm
	}
	return nil
}

func (m *ParkerState) GetMaximumTempertureAlarm() *Bool {
	if m != nil {
		return m.MaximumTempertureAlarm
	}
	return nil
}

func (m *ParkerState) GetCondensorTemperatureFailureAlarm() *Bool {
	if m != nil {
		return m.CondensorTemperatureFailureAlarm
	}
	return nil
}

func (m *ParkerState) GetCondensorPreAlarm() *Bool {
	if m != nil {
		return m.CondensorPreAlarm
	}
	return nil
}

func (m *ParkerState) GetDoorAlarm() *Bool {
	if m != nil {
		return m.DoorAlarm
	}
	return nil
}

func (m *ParkerState) GetMultipurposeInputAlarm() *Bool {
	if m != nil {
		return m.MultipurposeInputAlarm
	}
	return nil
}

func (m *ParkerState) GetCompressorBlockedAlarm() *Bool {
	if m != nil {
		return m.CompressorBlockedAlarm
	}
	return nil
}

func (m *ParkerState) GetPowerFailureAlarm() *Bool {
	if m != nil {
		return m.PowerFailureAlarm
	}
	return nil
}

func (m *ParkerState) GetRtcErrorAlarm() *Bool {
	if m != nil {
		return m.RtcErrorAlarm
	}
	return nil
}

func (m *ParkerState) GetEnergySavingRegulatorFlag() *Bool {
	if m != nil {
		return m.EnergySavingRegulatorFlag
	}
	return nil
}

func (m *ParkerState) GetEnergySavingRealTimeRegulatorFlag() *Bool {
	if m != nil {
		return m.EnergySavingRealTimeRegulatorFlag
	}
	return nil
}

func (m *ParkerState) GetServiceRequestRegulatorFlag() *Bool {
	if m != nil {
		return m.ServiceRequestRegulatorFlag
	}
	return nil
}

func (m *ParkerState) GetOnStandbyRegulatorFlag() *Bool {
	if m != nil {
		return m.OnStandbyRegulatorFlag
	}
	return nil
}

func (m *ParkerState) GetNewAlarmToReadRegulatorFlag() *Bool {
	if m != nil {
		return m.NewAlarmToReadRegulatorFlag
	}
	return nil
}

func (m *ParkerState) GetDefrostStatusRegulatorFlag() *Int64 {
	if m != nil {
		return m.DefrostStatusRegulatorFlag
	}
	return nil
}

func (m *ParkerState) GetActiveSetpoint() *Double {
	if m != nil {
		return m.ActiveSetpoint
	}
	return nil
}

func (m *ParkerState) GetTimeUntilDefrost() *Double {
	if m != nil {
		return m.TimeUntilDefrost
	}
	return nil
}

func (m *ParkerState) GetCurrentDefrostCounter() *Double {
	if m != nil {
		return m.CurrentDefrostCounter
	}
	return nil
}

func (m *ParkerState) GetCompressorDelay() *Double {
	if m != nil {
		return m.CompressorDelay
	}
	return nil
}

func (m *ParkerState) GetNumAlarmsInHistory() *Int64 {
	if m != nil {
		return m.NumAlarmsInHistory
	}
	return nil
}

func (m *ParkerState) GetEnergySavingStatus() *Bool {
	if m != nil {
		return m.EnergySavingStatus
	}
	return nil
}

func (m *ParkerState) GetServiceRequestStatus() *Bool {
	if m != nil {
		return m.ServiceRequestStatus
	}
	return nil
}

func (m *ParkerState) GetResistorsActivatedByAuxKeyStatus() *Bool {
	if m != nil {
		return m.ResistorsActivatedByAuxKeyStatus
	}
	return nil
}

func (m *ParkerState) GetEvaporatorValveState() *Bool {
	if m != nil {
		return m.EvaporatorValveState
	}
	return nil
}

func (m *ParkerState) GetOutputDefrostState() *Bool {
	if m != nil {
		return m.OutputDefrostState
	}
	return nil
}

func (m *ParkerState) GetOutputLuxState() *Bool {
	if m != nil {
		return m.OutputLuxState
	}
	return nil
}

func (m *ParkerState) GetOutputAuxState() *Bool {
	if m != nil {
		return m.OutputAuxState
	}
	return nil
}

func (m *ParkerState) GetResistorsState() *Bool {
	if m != nil {
		return m.ResistorsState
	}
	return nil
}

func (m *ParkerState) GetOutputAlarmState() *Bool {
	if m != nil {
		return m.OutputAlarmState
	}
	return nil
}

func (m *ParkerState) GetSecondCompressorState() *Bool {
	if m != nil {
		return m.SecondCompressorState
	}
	return nil
}

func (m *ParkerState) GetSetpoint() *Double {
	if m != nil {
		return m.Setpoint
	}
	return nil
}

func (m *ParkerState) GetClearAlarmHistory() *Int64 {
	if m != nil {
		return m.ClearAlarmHistory
	}
	return nil
}

func (m *ParkerState) GetClearnNewAlarmFlag() *Int64 {
	if m != nil {
		return m.ClearnNewAlarmFlag
	}
	return nil
}

func (m *ParkerState) GetHACCP0_Datetime() *Uint64 {
	if m != nil {
		return m.HACCP0_Datetime
	}
	return nil
}

func (m *ParkerState) GetHACCP0AlarmType() *Int64 {
	if m != nil {
		return m.HACCP0AlarmType
	}
	return nil
}

func (m *ParkerState) GetHACCP0Duration() *Double {
	if m != nil {
		return m.HACCP0Duration
	}
	return nil
}

func (m *ParkerState) GetHACCP0Temperature() *Double {
	if m != nil {
		return m.HACCP0Temperature
	}
	return nil
}

func (m *ParkerState) GetHACCP1_Datetime() *Uint64 {
	if m != nil {
		return m.HACCP1_Datetime
	}
	return nil
}

func (m *ParkerState) GetHACCP1AlarmType() *Int64 {
	if m != nil {
		return m.HACCP1AlarmType
	}
	return nil
}

func (m *ParkerState) GetHACCP1Duration() *Double {
	if m != nil {
		return m.HACCP1Duration
	}
	return nil
}

func (m *ParkerState) GetHACCP1Temperature() *Double {
	if m != nil {
		return m.HACCP1Temperature
	}
	return nil
}

func (m *ParkerState) GetHACCP2_Datetime() *Uint64 {
	if m != nil {
		return m.HACCP2_Datetime
	}
	return nil
}

func (m *ParkerState) GetHACCP2AlarmType() *Int64 {
	if m != nil {
		return m.HACCP2AlarmType
	}
	return nil
}

func (m *ParkerState) GetHACCP2Duration() *Double {
	if m != nil {
		return m.HACCP2Duration
	}
	return nil
}

func (m *ParkerState) GetHACCP2Temperature() *Double {
	if m != nil {
		return m.HACCP2Temperature
	}
	return nil
}

func (m *ParkerState) GetHACCP3_Datetime() *Uint64 {
	if m != nil {
		return m.HACCP3_Datetime
	}
	return nil
}

func (m *ParkerState) GetHACCP3AlarmType() *Int64 {
	if m != nil {
		return m.HACCP3AlarmType
	}
	return nil
}

func (m *ParkerState) GetHACCP3Duration() *Double {
	if m != nil {
		return m.HACCP3Duration
	}
	return nil
}

func (m *ParkerState) GetHACCP3Temperature() *Double {
	if m != nil {
		return m.HACCP3Temperature
	}
	return nil
}

func (m *ParkerState) GetHACCP4_Datetime() *Uint64 {
	if m != nil {
		return m.HACCP4_Datetime
	}
	return nil
}

func (m *ParkerState) GetHACCP4AlarmType() *Int64 {
	if m != nil {
		return m.HACCP4AlarmType
	}
	return nil
}

func (m *ParkerState) GetHACCP4Duration() *Double {
	if m != nil {
		return m.HACCP4Duration
	}
	return nil
}

func (m *ParkerState) GetHACCP4Temperature() *Double {
	if m != nil {
		return m.HACCP4Temperature
	}
	return nil
}

func (m *ParkerState) GetHACCP5_Datetime() *Uint64 {
	if m != nil {
		return m.HACCP5_Datetime
	}
	return nil
}

func (m *ParkerState) GetHACCP5AlarmType() *Int64 {
	if m != nil {
		return m.HACCP5AlarmType
	}
	return nil
}

func (m *ParkerState) GetHACCP5Duration() *Double {
	if m != nil {
		return m.HACCP5Duration
	}
	return nil
}

func (m *ParkerState) GetHACCP5Temperature() *Double {
	if m != nil {
		return m.HACCP5Temperature
	}
	return nil
}

func (m *ParkerState) GetHACCP6_Datetime() *Uint64 {
	if m != nil {
		return m.HACCP6_Datetime
	}
	return nil
}

func (m *ParkerState) GetHACCP6AlarmType() *Int64 {
	if m != nil {
		return m.HACCP6AlarmType
	}
	return nil
}

func (m *ParkerState) GetHACCP6Duration() *Double {
	if m != nil {
		return m.HACCP6Duration
	}
	return nil
}

func (m *ParkerState) GetHACCP6Temperature() *Double {
	if m != nil {
		return m.HACCP6Temperature
	}
	return nil
}

func (m *ParkerState) GetHACCP7_Datetime() *Uint64 {
	if m != nil {
		return m.HACCP7_Datetime
	}
	return nil
}

func (m *ParkerState) GetHACCP7AlarmType() *Int64 {
	if m != nil {
		return m.HACCP7AlarmType
	}
	return nil
}

func (m *ParkerState) GetHACCP7Duration() *Double {
	if m != nil {
		return m.HACCP7Duration
	}
	return nil
}

func (m *ParkerState) GetHACCP7Temperature() *Double {
	if m != nil {
		return m.HACCP7Temperature
	}
	return nil
}

func (m *ParkerState) GetHACCP8_Datetime() *Uint64 {
	if m != nil {
		return m.HACCP8_Datetime
	}
	return nil
}

func (m *ParkerState) GetHACCP8AlarmType() *Int64 {
	if m != nil {
		return m.HACCP8AlarmType
	}
	return nil
}

func (m *ParkerState) GetHACCP8Duration() *Double {
	if m != nil {
		return m.HACCP8Duration
	}
	return nil
}

func (m *ParkerState) GetHACCP8Temperature() *Double {
	if m != nil {
		return m.HACCP8Temperature
	}
	return nil
}

func (m *ParkerState) GetR1() *Double {
	if m != nil {
		return m.R1
	}
	return nil
}

func (m *ParkerState) GetR2() *Double {
	if m != nil {
		return m.R2
	}
	return nil
}

func (m *ParkerState) GetR4() *Double {
	if m != nil {
		return m.R4
	}
	return nil
}

func (m *ParkerState) GetC0() *Double {
	if m != nil {
		return m.C0
	}
	return nil
}

func (m *ParkerState) GetC1() *Double {
	if m != nil {
		return m.C1
	}
	return nil
}

func (m *ParkerState) GetD0() *Double {
	if m != nil {
		return m.D0
	}
	return nil
}

func (m *ParkerState) GetD3() *Double {
	if m != nil {
		return m.D3
	}
	return nil
}

func (m *ParkerState) GetD5() *Double {
	if m != nil {
		return m.D5
	}
	return nil
}

func (m *ParkerState) GetD7() *Double {
	if m != nil {
		return m.D7
	}
	return nil
}

func (m *ParkerState) GetD8() *Int64 {
	if m != nil {
		return m.D8
	}
	return nil
}

func (m *ParkerState) GetA0() *Int64 {
	if m != nil {
		return m.A0
	}
	return nil
}

func (m *ParkerState) GetA1() *Double {
	if m != nil {
		return m.A1
	}
	return nil
}

func (m *ParkerState) GetA2() *Int64 {
	if m != nil {
		return m.A2
	}
	return nil
}

func (m *ParkerState) GetA3() *Int64 {
	if m != nil {
		return m.A3
	}
	return nil
}

func (m *ParkerState) GetA4() *Double {
	if m != nil {
		return m.A4
	}
	return nil
}

func (m *ParkerState) GetA5() *Int64 {
	if m != nil {
		return m.A5
	}
	return nil
}

func (m *ParkerState) GetA6() *Double {
	if m != nil {
		return m.A6
	}
	return nil
}

func (m *ParkerState) GetA7() *Double {
	if m != nil {
		return m.A7
	}
	return nil
}

func (m *ParkerState) GetA8() *Double {
	if m != nil {
		return m.A8
	}
	return nil
}

func (m *ParkerState) GetA9() *Double {
	if m != nil {
		return m.A9
	}
	return nil
}

func (m *ParkerState) GetF0() *Int64 {
	if m != nil {
		return m.F0
	}
	return nil
}

func (m *ParkerState) GetF1() *Double {
	if m != nil {
		return m.F1
	}
	return nil
}

func (m *ParkerState) GetF2() *Int64 {
	if m != nil {
		return m.F2
	}
	return nil
}

func (m *ParkerState) GetF3() *Double {
	if m != nil {
		return m.F3
	}
	return nil
}

func (m *ParkerState) GetHd1() string {
	if m != nil {
		return m.Hd1
	}
	return ""
}

func (m *ParkerState) GetHd2() string {
	if m != nil {
		return m.Hd2
	}
	return ""
}

func (m *ParkerState) GetHd3() string {
	if m != nil {
		return m.Hd3
	}
	return ""
}

func (m *ParkerState) GetHd4() string {
	if m != nil {
		return m.Hd4
	}
	return ""
}

func (m *ParkerState) GetHd5() string {
	if m != nil {
		return m.Hd5
	}
	return ""
}

func (m *ParkerState) GetHd6() string {
	if m != nil {
		return m.Hd6
	}
	return ""
}

func init() {
	proto.RegisterType((*ParkerState)(nil), "xbospb.ParkerState")
}

func init() { proto.RegisterFile("parker.proto", fileDescriptor_parker_b0359a1265356f03) }

var fileDescriptor_parker_b0359a1265356f03 = []byte{
	// 1783 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x99, 0xf9, 0x7f, 0xdb, 0xb6,
	0x19, 0xc6, 0x3f, 0x6d, 0xb7, 0xac, 0x81, 0x6f, 0xfa, 0x82, 0x93, 0xc6, 0x73, 0xdb, 0xb5, 0xeb,
	0xda, 0xd5, 0x13, 0x0f, 0x51, 0x72, 0x96, 0x4b, 0x96, 0xa3, 0xd8, 0xcb, 0xe5, 0x48, 0x4e, 0xb2,
	0x2d, 0xcb, 0x38, 0x4a, 0x82, 0x6d, 0xce, 0x14, 0xa9, 0xf0, 0xf0, 0x91, 0xbf, 0x6c, 0x7f, 0xde,
	0x40, 0x00, 0x24, 0x41, 0xf1, 0x25, 0x7f, 0x4a, 0x82, 0xf7, 0x79, 0x1e, 0xe2, 0xfb, 0x12, 0x04,
	0xa0, 0x4f, 0xd0, 0xfc, 0xd4, 0x0e, 0x2e, 0x48, 0xb0, 0x3b, 0x0d, 0xfc, 0xc8, 0x57, 0x6e, 0x5d,
	0x0f, 0xfd, 0x70, 0x3a, 0xbc, 0xb3, 0xea, 0xc5, 0xae, 0x6b, 0x0f, 0x5d, 0x12, 0xdd, 0x4c, 0x49,
	0xc8, 0x8b, 0xdf, 0xfd, 0x4f, 0x47, 0x73, 0xc7, 0x4c, 0x3d, 0x88, 0xec, 0x88, 0x28, 0x87, 0x08,
	0x8f, 0xfc, 0xc9, 0x34, 0x20, 0x61, 0xe8, 0x07, 0xd6, 0x95, 0x1f, 0x5c, 0x38, 0xde, 0x99, 0x75,
	0xee, 0xc7, 0x41, 0x88, 0xbf, 0xd8, 0xf9, 0xe2, 0xa7, 0x39, 0x6d, 0x71, 0x97, 0xe7, 0xed, 0x1e,
	0xf8, 0x31, 0x0d, 0xeb, 0x6f, 0xe4, 0xfa, 0xf7, 0x5c, 0x7e, 0x98, 0xa8, 0x95, 0x3e, 0xda, 0x1e,
	0xb9, 0xc4, 0x0e, 0xac, 0xca, 0xbc, 0x2f, 0x59, 0xde, 0x42, 0x9a, 0x77, 0xe4, 0x45, 0xa6, 0xd1,
	0xbf, 0xcb, 0x4c, 0x5d, 0x38, 0xd3, 0x40, 0x8b, 0xc3, 0xf8, 0xf3, 0x67, 0x92, 0x84, 0x7a, 0x51,
	0xe0, 0xbb, 0xf8, 0x2b, 0x28, 0x63, 0x81, 0x8b, 0xba, 0x5c, 0xa3, 0x98, 0x68, 0x69, 0x4c, 0x4e,
	0x03, 0x3f, 0x8c, 0x32, 0xdb, 0x6f, 0x20, 0xdb, 0xa2, 0x50, 0x49, 0xbe, 0x30, 0xb2, 0x83, 0xc8,
	0xa2, 0x33, 0x71, 0xc2, 0xc8, 0xa7, 0x53, 0xfe, 0x2d, 0xe8, 0x63, 0xaa, 0x7e, 0x2a, 0x52, 0xf6,
	0xd0, 0x8a, 0xef, 0x59, 0x74, 0xd0, 0x1b, 0x0f, 0x6f, 0x92, 0x3f, 0xa3, 0x38, 0xc4, 0xb7, 0x20,
	0xe7, 0x92, 0xef, 0x0d, 0xb8, 0x6c, 0xc0, 0x54, 0x4a, 0x03, 0xcd, 0xbb, 0xce, 0xd9, 0x79, 0x94,
	0xba, 0x7e, 0x07, 0xb9, 0xe6, 0x98, 0x44, 0x38, 0xe8, 0xc3, 0xec, 0xf8, 0xda, 0xf2, 0xe3, 0x68,
	0x1a, 0x67, 0xb6, 0xaf, 0xc1, 0x87, 0x51, 0xdd, 0x6b, 0x26, 0x13, 0xd6, 0x27, 0x68, 0xcd, 0x23,
	0xd7, 0x91, 0x95, 0x37, 0x27, 0xf6, 0x22, 0x12, 0xe0, 0xdb, 0xe0, 0x7b, 0x56, 0x12, 0xed, 0x41,
	0xda, 0x21, 0xa6, 0x54, 0x9e, 0x22, 0x3c, 0xf6, 0xe9, 0x7b, 0x0d, 0xaf, 0x9c, 0x68, 0x74, 0x6e,
	0x39, 0x9e, 0x34, 0x07, 0xc4, 0x52, 0xe6, 0xd3, 0x94, 0x7d, 0xdf, 0x77, 0xfb, 0xeb, 0x89, 0x7a,
	0xc0, 0xc4, 0x47, 0x5e, 0x3e, 0x91, 0x43, 0xb4, 0x35, 0x89, 0xdd, 0xc8, 0x99, 0xc6, 0xc1, 0xd4,
	0x0f, 0x49, 0x31, 0x67, 0x0e, 0xc8, 0xd9, 0x94, 0xe5, 0x72, 0x12, 0xed, 0x86, 0xb4, 0xdc, 0x44,
	0xc2, 0x3c, 0x90, 0xb0, 0x9c, 0xcb, 0xb2, 0x6e, 0xac, 0x8b, 0x26, 0xa6, 0xfd, 0x10, 0xf6, 0x05,
	0xc0, 0xbe, 0xca, 0xa5, 0xa2, 0x1d, 0x22, 0xe1, 0x57, 0x34, 0x77, 0x6a, 0x7b, 0x61, 0xea, 0x5b,
	0x04, 0x7c, 0x28, 0x11, 0x08, 0xb9, 0x89, 0x96, 0xc5, 0x03, 0x2f, 0x8c, 0xd4, 0xb3, 0x04, 0x78,
	0x16, 0xb9, 0xea, 0xb9, 0x21, 0x7c, 0x8f, 0xd1, 0xea, 0xc8, 0x1e, 0x3a, 0x1e, 0x89, 0xac, 0x88,
	0x4c, 0xa6, 0x24, 0xa0, 0xa3, 0x01, 0xc1, 0xcb, 0xf0, 0x5b, 0x13, 0xd2, 0x93, 0x5c, 0x49, 0xdf,
	0xda, 0x06, 0xb9, 0xb4, 0xa7, 0x3e, 0xfd, 0x27, 0x6d, 0x92, 0x9c, 0xb1, 0x02, 0x66, 0xac, 0xe7,
	0x6a, 0x39, 0xa6, 0x8b, 0xd6, 0xe9, 0x8a, 0x72, 0x5c, 0xc7, 0x0e, 0x6e, 0x0a, 0x29, 0x0a, 0x98,
	0xb2, 0x96, 0x89, 0xe5, 0x90, 0x47, 0x68, 0x8d, 0x6e, 0x44, 0x43, 0xa2, 0x5a, 0xa7, 0xb6, 0xe3,
	0xd2, 0x11, 0xcb, 0x76, 0xed, 0x60, 0x82, 0x57, 0x81, 0x46, 0x28, 0x5c, 0xd9, 0xe3, 0xc2, 0x4e,
	0xa2, 0xcb, 0xfc, 0xda, 0x8c, 0x7f, 0xad, 0xd2, 0xaf, 0x81, 0x7e, 0x7d, 0xc6, 0xbf, 0x5e, 0xe9,
	0xd7, 0x0b, 0xfe, 0x64, 0xe9, 0x3a, 0x9e, 0x33, 0x89, 0x27, 0x72, 0x0b, 0x44, 0xc8, 0x06, 0xb8,
	0x74, 0xb9, 0x5c, 0x6a, 0x02, 0x4f, 0xea, 0x21, 0x3c, 0xb1, 0xaf, 0xa5, 0x24, 0x29, 0x68, 0x13,
	0x08, 0xda, 0x10, 0xea, 0x93, 0x4c, 0xcc, 0x73, 0x3e, 0xa0, 0xef, 0xe9, 0x2e, 0x37, 0x26, 0x5e,
	0x58, 0x7c, 0xb9, 0x33, 0x80, 0x18, 0x88, 0xdc, 0xc9, 0x8c, 0xd2, 0xec, 0x0a, 0xb8, 0x0f, 0xe8,
	0xda, 0xcb, 0xc2, 0xa7, 0x59, 0xd8, 0x16, 0x10, 0xb6, 0x92, 0x09, 0x8f, 0x53, 0xf7, 0x2f, 0x08,
	0xb1, 0xed, 0x82, 0x9b, 0xee, 0x00, 0xa6, 0xdb, 0x49, 0x3d, 0xef, 0x47, 0x79, 0x53, 0xe0, 0xd6,
	0xbb, 0x60, 0x3f, 0x66, 0xf7, 0x84, 0x2c, 0x47, 0xda, 0x12, 0x86, 0xae, 0x3f, 0xba, 0x20, 0x63,
	0x91, 0xf3, 0x0d, 0x94, 0x93, 0xab, 0xf7, 0xb9, 0x38, 0x43, 0x9f, 0xfa, 0x57, 0xf4, 0xe8, 0x29,
	0xf6, 0xf1, 0x1e, 0x84, 0xce, 0x84, 0x85, 0xc6, 0x19, 0x68, 0x29, 0x88, 0x46, 0x16, 0x09, 0x82,
	0x8c, 0x7f, 0x1b, 0x70, 0x2e, 0x50, 0xd1, 0xd3, 0x44, 0xc3, 0x5d, 0x2f, 0xd1, 0x37, 0xc4, 0x23,
	0xc1, 0x19, 0x3d, 0x45, 0xec, 0xcb, 0xe4, 0xe0, 0x0c, 0xc8, 0x59, 0xec, 0xb2, 0xcf, 0xf6, 0xd4,
	0xb5, 0xcf, 0xf0, 0xef, 0x81, 0x88, 0x2d, 0xee, 0x18, 0x30, 0x43, 0x3f, 0xd5, 0xf7, 0xa8, 0x5c,
	0xb1, 0xd0, 0x8f, 0xb3, 0x71, 0xb6, 0x6b, 0x45, 0xce, 0x84, 0xcc, 0x06, 0xef, 0x00, 0xc1, 0xdf,
	0x16, 0x83, 0x6d, 0xf7, 0x84, 0x1a, 0x8b, 0x0f, 0x78, 0x83, 0xb6, 0x43, 0x12, 0x5c, 0x3a, 0xa3,
	0x24, 0xf0, 0x53, 0x4c, 0xc2, 0x68, 0x36, 0xf8, 0x5b, 0x20, 0xf8, 0xae, 0xf0, 0xf4, 0xb9, 0xa5,
	0x18, 0xf9, 0x0c, 0x6d, 0x49, 0x87, 0xe9, 0x4c, 0xda, 0x77, 0xd0, 0xfb, 0xcb, 0xce, 0xd4, 0x62,
	0xd0, 0x00, 0xed, 0x78, 0xe4, 0x8a, 0xf7, 0xde, 0x8a, 0xfc, 0x84, 0x7d, 0x3c, 0x9b, 0xf7, 0x3d,
	0x34, 0x3b, 0xea, 0x62, 0x6f, 0xe3, 0xc4, 0xa7, 0xd0, 0xe3, 0x62, 0xe8, 0x31, 0xba, 0x57, 0x3c,
	0x2d, 0x66, 0x13, 0xff, 0x00, 0x9d, 0xc4, 0x77, 0xc6, 0xf2, 0xb9, 0x51, 0x4c, 0x6c, 0xa1, 0x25,
	0x7b, 0x14, 0x39, 0x97, 0xc4, 0x0a, 0x49, 0x34, 0xf5, 0x1d, 0x2f, 0xc2, 0x3f, 0x80, 0xfb, 0xe9,
	0x22, 0x97, 0x0d, 0x84, 0x8a, 0xae, 0x4f, 0x85, 0xbd, 0x49, 0x7a, 0x32, 0x3b, 0x6e, 0x7a, 0x86,
	0xe1, 0x1f, 0x41, 0xef, 0x72, 0xa2, 0x7c, 0x9b, 0x08, 0xc5, 0x09, 0x46, 0xbf, 0x92, 0xcd, 0x51,
	0x1c, 0x04, 0xc4, 0x2b, 0x5f, 0x07, 0xfe, 0x08, 0x1f, 0x0a, 0x42, 0x3e, 0x73, 0x23, 0xd8, 0x43,
	0xd2, 0xc9, 0x4a, 0xa3, 0x5c, 0xfb, 0x06, 0xff, 0x04, 0x06, 0x2c, 0xe5, 0xba, 0x83, 0x44, 0x96,
	0x1c, 0xc0, 0x1e, 0xdd, 0xfc, 0xd8, 0x0b, 0x0a, 0xe9, 0xe7, 0x6e, 0x9d, 0xb3, 0xfb, 0xd4, 0x0d,
	0xfe, 0x13, 0xd4, 0x43, 0x85, 0x6a, 0xd9, 0x6b, 0x09, 0x8f, 0xbc, 0x43, 0x2e, 0x4c, 0x36, 0xf3,
	0xe2, 0xfa, 0x16, 0xa7, 0xea, 0xcf, 0xd0, 0x66, 0x2e, 0xaf, 0x66, 0x71, 0xb2, 0xee, 0xa3, 0x8d,
	0xd9, 0xe5, 0x2b, 0x12, 0x7e, 0x01, 0x12, 0xd6, 0x8a, 0xcb, 0x56, 0x64, 0x7c, 0x44, 0x3f, 0x64,
	0xd7, 0x45, 0x8b, 0xbd, 0x22, 0x7a, 0xad, 0x1e, 0x5b, 0x74, 0xed, 0x26, 0xd7, 0xb4, 0x0b, 0x92,
	0x5d, 0x08, 0xff, 0x0c, 0x6d, 0xc0, 0x99, 0xb5, 0x93, 0x3a, 0xf7, 0x6f, 0x3a, 0xf1, 0xf5, 0x73,
	0x72, 0x93, 0x4f, 0x51, 0x3a, 0xbb, 0x2f, 0x6d, 0x37, 0x59, 0x28, 0xc9, 0xcd, 0x1d, 0xff, 0x0a,
	0x4d, 0x31, 0xd7, 0xbe, 0x4b, 0xa4, 0xfc, 0x8e, 0x4f, 0xdb, 0x04, 0xdc, 0x74, 0x08, 0xde, 0x85,
	0xda, 0x54, 0xba, 0xe8, 0x10, 0xe9, 0xe2, 0xe2, 0x52, 0x24, 0xee, 0xfd, 0x4b, 0xf5, 0xc5, 0xe5,
	0x45, 0x7c, 0x3d, 0xeb, 0xb3, 0x33, 0x5f, 0xa3, 0xda, 0xd7, 0x49, 0x7d, 0x4d, 0xba, 0x77, 0x66,
	0x2d, 0xe5, 0x36, 0x15, 0xb2, 0x65, 0x22, 0x6e, 0xbb, 0x8f, 0x94, 0xf4, 0x71, 0xec, 0x9b, 0xe7,
	0x4e, 0x0d, 0xba, 0x0c, 0x8a, 0x07, 0x26, 0x32, 0xee, 0x3d, 0x40, 0x9b, 0x21, 0x49, 0x0e, 0x30,
	0x6b, 0xe6, 0x3a, 0x49, 0xb0, 0x0e, 0xdd, 0x6b, 0xb9, 0xb8, 0x5b, 0xb8, 0x53, 0x12, 0xe5, 0x67,
	0xf4, 0x75, 0xf6, 0x11, 0x1b, 0xe0, 0x47, 0x90, 0xd5, 0x95, 0x87, 0xf4, 0x64, 0x65, 0x3f, 0x97,
	0xf8, 0x64, 0xd3, 0xb5, 0xdf, 0x84, 0xd6, 0xfe, 0x0a, 0x53, 0xb2, 0xe9, 0xa6, 0x4b, 0x9f, 0x7e,
	0x3c, 0x6c, 0xd0, 0xb3, 0xf2, 0x4d, 0x8e, 0x6d, 0x40, 0x26, 0xf8, 0xf1, 0x70, 0xed, 0x2b, 0xb1,
	0xb3, 0xa5, 0x1b, 0xcf, 0x61, 0xa7, 0xdb, 0x3d, 0x6e, 0x58, 0x07, 0x74, 0xee, 0xc9, 0x06, 0x81,
	0x5b, 0xc5, 0x39, 0xbf, 0x75, 0xf8, 0xcf, 0x1d, 0x2e, 0x4b, 0x55, 0xc9, 0x9d, 0x5b, 0x18, 0xc5,
	0xde, 0x4a, 0x7f, 0x5e, 0xe2, 0x36, 0xf8, 0x0b, 0x84, 0xeb, 0xf8, 0x6e, 0x4a, 0x55, 0xd2, 0x33,
	0xc7, 0x31, 0x5d, 0xa5, 0x8e, 0xef, 0xe1, 0x3d, 0x78, 0xb3, 0x13, 0xcf, 0x14, 0x2a, 0xda, 0x2d,
	0x45, 0x18, 0xe5, 0x8b, 0xe7, 0x7d, 0xd0, 0x2b, 0x66, 0x27, 0xdf, 0x3a, 0xd3, 0xe7, 0xaa, 0x39,
	0xeb, 0x5f, 0x6b, 0x58, 0xd5, 0x12, 0xab, 0x2a, 0xb3, 0x3e, 0xa8, 0x66, 0x55, 0xcb, 0xac, 0x6a,
	0xce, 0xfa, 0xb0, 0x86, 0x55, 0x2d, 0xb1, 0xaa, 0x05, 0xd6, 0x47, 0x35, 0xac, 0x2a, 0xc4, 0xaa,
	0xe5, 0xac, 0x8f, 0x6b, 0x58, 0xb5, 0x12, 0xab, 0x26, 0xb3, 0x3e, 0xa9, 0x66, 0xd5, 0xca, 0xac,
	0x5a, 0xce, 0xda, 0xa9, 0x61, 0xd5, 0x4a, 0xac, 0x5a, 0x81, 0x75, 0xbf, 0x86, 0x55, 0x83, 0x58,
	0xf5, 0x9c, 0xb5, 0x5b, 0xc3, 0xaa, 0x97, 0x58, 0x75, 0x99, 0xf5, 0xa0, 0x9a, 0x55, 0x2f, 0xb3,
	0xea, 0x39, 0xeb, 0xd3, 0x1a, 0x56, 0xbd, 0xc4, 0xaa, 0x17, 0x58, 0x7b, 0x35, 0xac, 0x3a, 0xc4,
	0x6a, 0xe4, 0xac, 0xcf, 0x6a, 0x58, 0x8d, 0x12, 0xab, 0x21, 0xb3, 0x1e, 0x56, 0xb3, 0x1a, 0x65,
	0x56, 0x23, 0x67, 0x3d, 0xaa, 0x61, 0x35, 0x4a, 0xac, 0x46, 0x81, 0xf5, 0x6f, 0x35, 0xac, 0x06,
	0xc4, 0xda, 0xcc, 0x59, 0x9f, 0xd7, 0xb0, 0x36, 0x4b, 0xac, 0x4d, 0x99, 0xf5, 0x45, 0x35, 0x6b,
	0xb3, 0xcc, 0xda, 0xcc, 0x59, 0x5f, 0xd6, 0xb0, 0x36, 0x4b, 0xac, 0xcd, 0x02, 0xeb, 0xab, 0x1a,
	0xd6, 0x26, 0xc4, 0x6a, 0xe6, 0xac, 0xaf, 0x6b, 0x58, 0xcd, 0x12, 0xab, 0x29, 0xb3, 0x1e, 0x57,
	0xb3, 0x9a, 0x65, 0x56, 0x33, 0x67, 0x7d, 0x53, 0xc3, 0x6a, 0x96, 0x58, 0xcd, 0x02, 0x6b, 0xbf,
	0x86, 0xd5, 0x84, 0x58, 0x5b, 0x39, 0xeb, 0xa0, 0x86, 0xb5, 0x55, 0x62, 0x6d, 0xc9, 0xac, 0x27,
	0xd5, 0xac, 0xad, 0x32, 0x6b, 0x2b, 0x67, 0x7d, 0x5b, 0xc3, 0xda, 0x2a, 0xb1, 0xb6, 0x0a, 0xac,
	0xef, 0x6a, 0x58, 0x5b, 0x10, 0x6b, 0x3b, 0x67, 0x7d, 0x5f, 0xc3, 0xda, 0x2e, 0xb1, 0xb6, 0x65,
	0xd6, 0xbf, 0x57, 0xb3, 0xb6, 0xcb, 0xac, 0xed, 0x9c, 0xf5, 0x1f, 0x35, 0xac, 0xed, 0x12, 0x6b,
	0xbb, 0xc0, 0xfa, 0xcf, 0x1a, 0xd6, 0xb6, 0xcc, 0xba, 0x8d, 0xbe, 0x0c, 0x54, 0xfc, 0x01, 0x94,
	0xd3, 0x0a, 0xab, 0x6b, 0xf8, 0x5f, 0x15, 0x75, 0x8d, 0xd5, 0x0d, 0xfc, 0xb1, 0xa2, 0x6e, 0x24,
	0xf5, 0x6e, 0x03, 0xff, 0x1b, 0xae, 0x77, 0x1b, 0xac, 0xae, 0x62, 0xab, 0xa2, 0xce, 0x9e, 0x3f,
	0x6e, 0xe0, 0xff, 0xc0, 0xf5, 0x31, 0xf3, 0x8f, 0x75, 0x6c, 0x57, 0xd4, 0x75, 0x56, 0x6f, 0xe2,
	0x61, 0x45, 0xbd, 0xc9, 0xea, 0x2d, 0x3c, 0xaa, 0xa8, 0xb7, 0x94, 0x7b, 0xb4, 0xde, 0xc6, 0x63,
	0xe8, 0x1d, 0xd2, 0x42, 0x52, 0xee, 0x34, 0x30, 0x01, 0xcb, 0x1d, 0x36, 0xbb, 0x8e, 0x8a, 0x4f,
	0xe1, 0xf4, 0x8e, 0xca, 0xec, 0x1a, 0x3e, 0x83, 0xed, 0x1a, 0x2b, 0xeb, 0xf8, 0x1c, 0x2e, 0x33,
	0xb6, 0x8e, 0x81, 0x9d, 0x8a, 0x74, 0x83, 0xd9, 0x9b, 0xf8, 0xbf, 0xb0, 0x9d, 0xa1, 0x77, 0x4c,
	0x7c, 0x51, 0x61, 0x37, 0x59, 0xbd, 0x85, 0xdd, 0x8a, 0x7a, 0x8b, 0xd5, 0xdb, 0x78, 0x52, 0x51,
	0x6f, 0xb3, 0xfa, 0x1e, 0xf6, 0x2a, 0xea, 0x7b, 0xc9, 0xf4, 0x7a, 0x0d, 0xec, 0x83, 0xd3, 0xeb,
	0xb1, 0xde, 0xf5, 0x54, 0x3c, 0x85, 0xed, 0x3d, 0xd6, 0xbb, 0x9e, 0x86, 0x3f, 0xc1, 0x76, 0xb6,
	0x30, 0x7b, 0x3a, 0x0e, 0x2a, 0xec, 0xba, 0xb2, 0x8c, 0xbe, 0x3a, 0x1c, 0xab, 0x38, 0xa4, 0x82,
	0xdb, 0xfd, 0xe4, 0xaf, 0x7c, 0x44, 0xc3, 0x51, 0x3a, 0xa2, 0xf1, 0x11, 0x1d, 0xc7, 0xe9, 0x88,
	0x70, 0x19, 0xf8, 0x32, 0x1d, 0x31, 0xf8, 0x48, 0x13, 0x5f, 0xa5, 0x23, 0x4d, 0x3e, 0x62, 0xe2,
	0xeb, 0x74, 0xc4, 0x1c, 0xde, 0x62, 0xff, 0x83, 0xa3, 0xff, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x72,
	0x64, 0x85, 0xbf, 0xee, 0x19, 0x00, 0x00,
}
