// Code generated by protoc-gen-go. DO NOT EDIT.
// source: system_monitor.proto

package xbospb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BasicServerStatus struct {
	// unit:ns
	Time     uint64 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Hostname string `protobuf:"bytes,6,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// index is the CPU number;
	// unit: percent
	CpuLoad []*Double `protobuf:"bytes,2,rep,name=cpu_load,json=cpuLoad,proto3" json:"cpu_load,omitempty"`
	// available physical memory
	// unit: bytes
	PhysMemAvailable *Int64 `protobuf:"bytes,3,opt,name=phys_mem_available,json=physMemAvailable,proto3" json:"phys_mem_available,omitempty"`
	// disk usage of /
	// unit: percent
	DiskUsage *Double `protobuf:"bytes,4,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	// disk usage of /
	// unit: bytes
	DiskAvailable        *Double  `protobuf:"bytes,5,opt,name=disk_available,json=diskAvailable,proto3" json:"disk_available,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BasicServerStatus) Reset()         { *m = BasicServerStatus{} }
func (m *BasicServerStatus) String() string { return proto.CompactTextString(m) }
func (*BasicServerStatus) ProtoMessage()    {}
func (*BasicServerStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_system_monitor_19a2aa99c969a414, []int{0}
}
func (m *BasicServerStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicServerStatus.Unmarshal(m, b)
}
func (m *BasicServerStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicServerStatus.Marshal(b, m, deterministic)
}
func (dst *BasicServerStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicServerStatus.Merge(dst, src)
}
func (m *BasicServerStatus) XXX_Size() int {
	return xxx_messageInfo_BasicServerStatus.Size(m)
}
func (m *BasicServerStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicServerStatus.DiscardUnknown(m)
}

var xxx_messageInfo_BasicServerStatus proto.InternalMessageInfo

func (m *BasicServerStatus) GetTime() uint64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *BasicServerStatus) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *BasicServerStatus) GetCpuLoad() []*Double {
	if m != nil {
		return m.CpuLoad
	}
	return nil
}

func (m *BasicServerStatus) GetPhysMemAvailable() *Int64 {
	if m != nil {
		return m.PhysMemAvailable
	}
	return nil
}

func (m *BasicServerStatus) GetDiskUsage() *Double {
	if m != nil {
		return m.DiskUsage
	}
	return nil
}

func (m *BasicServerStatus) GetDiskAvailable() *Double {
	if m != nil {
		return m.DiskAvailable
	}
	return nil
}

func init() {
	proto.RegisterType((*BasicServerStatus)(nil), "xbospb.BasicServerStatus")
}

func init() {
	proto.RegisterFile("system_monitor.proto", fileDescriptor_system_monitor_19a2aa99c969a414)
}

var fileDescriptor_system_monitor_19a2aa99c969a414 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x90, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x86, 0xd5, 0x36, 0x84, 0xf6, 0xaa, 0x56, 0x70, 0x30, 0x44, 0x9d, 0x2a, 0xa6, 0x32, 0x90,
	0xa1, 0x7c, 0x2c, 0x4c, 0x20, 0x16, 0x24, 0x58, 0x52, 0x31, 0x47, 0x4e, 0x6b, 0x51, 0x8b, 0x38,
	0xb6, 0x72, 0xe7, 0x8a, 0xfc, 0x0c, 0xfe, 0x31, 0x8e, 0xab, 0x06, 0x09, 0x75, 0xb3, 0xef, 0x7d,
	0x5e, 0x3f, 0x27, 0xc3, 0x25, 0x35, 0xc4, 0x52, 0xe7, 0xda, 0x54, 0x8a, 0x4d, 0x9d, 0xda, 0xda,
	0xb0, 0xc1, 0xf8, 0xbb, 0x30, 0x64, 0x8b, 0xd9, 0x45, 0xe5, 0xca, 0x52, 0x14, 0xa5, 0xe4, 0xc6,
	0x4a, 0xda, 0x87, 0x57, 0x3f, 0x7d, 0x38, 0x7f, 0x16, 0xa4, 0xd6, 0x2b, 0x59, 0xef, 0x64, 0xbd,
	0x62, 0xc1, 0x8e, 0x10, 0x21, 0x62, 0xa5, 0x65, 0xd2, 0x9b, 0xf7, 0x16, 0x51, 0x16, 0xce, 0x38,
	0x83, 0xe1, 0xd6, 0x10, 0x57, 0xc2, 0xcf, 0x63, 0x3f, 0x1f, 0x65, 0xdd, 0x1d, 0xaf, 0x61, 0xb8,
	0xb6, 0x2e, 0x2f, 0x8d, 0xd8, 0x24, 0xfd, 0xf9, 0x60, 0x31, 0x5e, 0x4e, 0xd3, 0xbd, 0x35, 0x7d,
	0x31, 0xce, 0x2b, 0xb3, 0x53, 0x9f, 0xbf, 0xf9, 0x18, 0x1f, 0x01, 0xed, 0xb6, 0xa1, 0x5c, 0xfb,
	0x3d, 0xc5, 0x4e, 0xa8, 0xb0, 0x51, 0x32, 0xf0, 0x0f, 0x8e, 0x97, 0x93, 0x43, 0xe9, 0xb5, 0xe2,
	0x87, 0xbb, 0xec, 0xac, 0x05, 0xdf, 0xa5, 0x7e, 0x3a, 0x60, 0x78, 0x03, 0xb0, 0x51, 0xf4, 0x95,
	0x3b, 0x12, 0x9f, 0x32, 0x89, 0x42, 0xe9, 0xbf, 0x69, 0xd4, 0x12, 0x1f, 0x2d, 0x80, 0xf7, 0x30,
	0x0d, 0xf8, 0x9f, 0xe7, 0xe4, 0x68, 0x65, 0xd2, 0x52, 0x9d, 0xa5, 0x88, 0xc3, 0xd7, 0xdc, 0xfe,
	0x06, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x8d, 0x79, 0xbc, 0x4f, 0x01, 0x00, 0x00,
}
